### ISSUE TITLE
Support basic git workflows

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/luarocks-tag-release#11]
Some less heavily developed plugins want to stick with the basic git workflow, without branches or PRs or tags (see https://github.com/ibhagwan/fzf-lua/pull/640).

To support such workflows, this action could add a `version` input to override the tag.

Workflows that use this input could use a schedule to trigger LuaRocks uploads:

```yaml
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * *' # runs daily at 00:00
```

...with a check that ensures the action is only run if the last commit more recent than the schedule, using:

```console
> git show --format="%ci %cr" master
2023-02-13 09:48:28 +0000 7 hours ago
```
- [ ] TODO: Figure out how to use this with an [if conditional](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif) to stop the job if the last commit is older than the schedule's period.

Workflows could set the luarocks package version based on the number of commits  on the `main` branch:

```yaml
 - name: Set env
   run: echo "LUAROCKS_VERSION='0.0.$(git log --oneline | wc -l)'" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

```console
> git log --oneline | wc -l
576
```
