### ISSUE TITLE
Idea: test script to run after local luarocks install

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/luarocks-tag-release#64]
`luarocks test`/`busted` uses the source directories (defined in `lpath` of the `.busted` file) to run tests, not the luarocks package as defined in the rockspec.

It would be nice to have a way to run some tests against the installed package, to validate that the package works as expected.

For this purpose, a simple `validate-install-cmd` input may suffice.
It could be something like:

```yaml
with:
  validate-install-cmd: |
    nvim -c <load-installed-package> -l require('my-package').setup()
```
